#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

coreos:
  oem:
    id: vagrant
    name: CoreOS.box for Vagrant
    version-id: %VERSION_ID%+%BUILD_ID%
    home-url: https://vagrantcloud.com/yungsang/coreos
    bug-report-url: https://github.com/YungSang/coreos-packer

  units:
    - name: motdgen.service
      command: start
      content: |
        [Unit]
        Description=Generate /run/coreos/motd
        Before=systemd-user-sessions.service

        [Service]
        Type=oneshot
        ExecStart=/usr/share/oem/bin/motdgen

    - name: coreos-cloudinit-vagrant-mkdir.service
      command: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        ExecStart=/bin/mkdir -p /var/lib/coreos-vagrant

    - name: coreos-cloudinit-vagrant-user.path
      command: start
      runtime: yes
      content: |
        [Path]
        PathExists=/var/lib/coreos-vagrant/vagrantfile-user-data
        Unit=user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service

    - name: docker-tcp.socket
      command: start
      runtime: no
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target

    - name: docker.service
      command: start

    - name: docker-enter-install.service
      command: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        ExecStartPre=/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/ln -s -f /usr/share/oem/bin/docker-enter /opt/bin/docker-enter
        ExecStart=/usr/bin/ln -s -f /usr/share/oem/bin/docker-enter /opt/bin/docker-attach
